APPLICATION:
  name: 'coreApp'
  defaultPwd: 'bDGGir52C5zMAkSU0ufZwZcndxNRJKsPTtUdAGpOivq6e5F22UIPpGOa569A1dnBXKcV3vrPFfv6E7KJ4qdI+22TMBe77pAy3V0fvJpZif+CqdjvGHCsKH3IBHhyzzRzbYbqrMDPBu0EeZTjRK9RiAntfk82ocvEt52f6gTlO6w='
